In [28]:
%load_ext pycodestyle_magic


The pycodestyle_magic extension is already loaded. To reload it, use:
  %reload_ext pycodestyle_magic


In [29]:
%pycodestyle_on

In [30]:
import torch
from torch import nn

In [31]:
class LinearRegression(nn.Module):

    def __init__(self, lr):
        super().__init__()
        self.lr = lr
        self.net = nn.LazyLinear(1)
        self.net.weight.data.normal_(0, 0.01)
        self.net.bias.data.fill_(0)

    def forward(self, X):
        return self.net(X)

    def loss(self, y_hat, y):
        fn = nn.MSELoss()
        return fn(y_hat, y)

    def config_optimizers(self):
        return torch.optim.SGD(self.parameters(), self.lr)

In [32]:
class SyntheticData():
    def __init__(self, w, b, noise=0.01,batch_size=32, num_of_training_data=10000
                  , num_of_validation_data=10000, device="cpu"):
        self.w = w
        self.b = b
        self.batch_sizindiciese = batch_size
        self.num_of_training_data = num_of_training_data
        self.num_of_validation_data = num_of_validation_data
        self.device = device
        self.n = self.num_of_training_data + self.num_of_validation_data
        self.X = torch.randn((self.n, len(self.w)))
        self.noise = torch.randn(self.n, 1) * noise
        self.Y = torch.matmul(self.X, self.w.reshape(-1, 1)) + self.b + self.noise

    def get_dataloader(self, train):
        indicies = slice(0, self.num_of_training_data) if train else slice(self.num_of_training_data, None)
        dataset = torch.utils.data.TensorDataset(self.X[indicies], self.Y[indicies])
        return torch.utils.data.DataLoader(dataset, batch_size=self.batch_size, shuffle=train)

    def training_data(self):
        return self.get_dataloader(True)

2:40: E231 missing whitespace after ','
2:80: E501 line too long (81 > 79 characters)
2:82: E203 whitespace before ','
3:19: E127 continuation line over-indented for visual indent
13:80: E501 line too long (82 > 79 characters)
16:80: E501 line too long (107 > 79 characters)
17:80: E501 line too long (84 > 79 characters)
18:80: E501 line too long (94 > 79 characters)


In [26]:
def Training(data, model, optim):
    model.train()

    for (X, y) in data.training_data():

        pred = model(X)
        loss = model.loss(pred, y)

        loss.backward()
        optim.step()
        optim.zero_grad()


12:1: W391 blank line at end of file


In [12]:
data = SyntheticData(torch.tensor([2, -3.4]), 5)
print(data.X[:3], data.Y[:3])
model = LinearRegression(0.03)
optim = model.config_optimizers()
for epoch in range(10):
    Training(data, model, optim)

tensor([[-0.9285, -2.3333],
        [-0.4462, -1.3247],
        [ 0.3506,  0.7902]]) tensor([[11.0679],
        [ 8.6148],
        [ 3.0177]])


In [13]:
model.net.weight

Parameter containing:
tensor([[ 2.0001, -3.4002]], requires_grad=True)

In [27]:
model(torch.tensor((2.2685,  1.7695)))

tensor([3.5200], grad_fn=<ViewBackward0>)